flowchart TD
%% generated in 0.01s
    adapters__js["adapters.js<br/>12 funcs"]
    adapters__python["adapters.python<br/>202 funcs"]
    examples__reference_adapters["examples.reference_adapters<br/>11 funcs"]
    v7__examples["v7.examples<br/>152 funcs"]
    v8__examples["v8.examples<br/>123 funcs"]
    v8__examples ==>|16| v7__examples
    v8__examples ==>|9| adapters__python
    adapters__python ==>|7| v7__examples
    adapters__python ==>|4| adapters__js
    examples__reference_adapters -->|1| v7__examples
