flowchart TD
%% generated in 0.09s
    adapters__conformance["adapters.conformance<br/>7 funcs"]
    adapters__java["adapters.java<br/>4 funcs"]
    adapters__js["adapters.js<br/>12 funcs"]
    adapters__perl["adapters.perl<br/>4 funcs"]
    adapters__python["adapters.python<br/>2121 funcs"]
    examples__matrix["examples.matrix<br/>3 funcs"]
    scripts__cc_gate["scripts.cc_gate<br/>3 funcs"]
    scripts__extraction_audit["scripts.extraction_audit<br/>12 funcs"]
    scripts__lint_connectors["scripts.lint_connectors<br/>6 funcs"]
    scripts__repin_connectors["scripts.repin_connectors<br/>7 funcs"]
    scripts__test_pypi_install["scripts.test_pypi_install<br/>2 funcs"]
    scripts__transport_swap_proof["scripts.transport_swap_proof<br/>5 funcs"]
    security__mesh_probe["security.mesh-probe<br/>3 funcs"]
    v1__js["v1.js<br/>57 funcs"]
    xlang__driver["xlang.driver<br/>3 funcs"]
    xlang__emit_contracts["xlang.emit_contracts<br/>1 funcs"]
    xlang__peer["xlang.peer<br/>27 funcs"]
    adapters__python ==>|136| scripts__test_pypi_install
    scripts__extraction_audit ==>|20| scripts__test_pypi_install
    adapters__python ==>|17| adapters__js
    scripts__repin_connectors ==>|12| scripts__test_pypi_install
    adapters__conformance ==>|11| scripts__test_pypi_install
    scripts__transport_swap_proof ==>|9| scripts__test_pypi_install
    examples__matrix ==>|7| scripts__test_pypi_install
    scripts__lint_connectors ==>|6| scripts__test_pypi_install
    adapters__python ==>|6| v1__js
    scripts__cc_gate ==>|4| scripts__test_pypi_install
    xlang__driver -->|3| scripts__test_pypi_install
    examples__matrix -->|2| adapters__python
    xlang__emit_contracts -->|2| adapters__python
    xlang__peer -->|2| scripts__test_pypi_install
    security__mesh_probe -->|1| scripts__test_pypi_install
    scripts__lint_connectors -->|1| adapters__python
    scripts__extraction_audit -->|1| adapters__python
    adapters__conformance -->|1| adapters__python
    adapters__python -->|1| adapters__perl
    adapters__python -->|1| adapters__java
    xlang__driver -->|1| adapters__python
