flowchart TD
%% generated in 0.02s
    adapters__java["adapters.java<br/>4 funcs"]
    adapters__js["adapters.js<br/>12 funcs"]
    adapters__python["adapters.python<br/>1082 funcs"]
    examples__matrix["examples.matrix<br/>3 funcs"]
    adapters__python ==>|4| adapters__js
    examples__matrix -->|1| adapters__python
    adapters__python -->|1| adapters__java
